services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpac.security.enable=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data


volumes:
  esdata:
    driver: local
